# Generated by Django 3.0.6 on 2020-12-03 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoExtra',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('campos_extra', models.ManyToManyField(blank=True, related_name='grupos', to='contacto.CampoExtra')),
                ('cuenta', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='marketing.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=100)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='contacto.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Campo_Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=1000)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacto.CampoExtra')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_extra', to='contacto.Contacto')),
            ],
            options={
                'ordering': ['contacto'],
            },
        ),
    ]
