# Generated by Django 3.0.6 on 2020-10-29 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoExtra',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cmapos_extra', models.ManyToManyField(blank=True, to='contacto.CampoExtra')),
                ('cuenta', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cuenta_del_grupo', to='marketing.Cuenta')),
            ],
            options={
                'ordering': ['cuenta'],
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=100)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='contacto.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Campo_Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=70)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacto.CampoExtra')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_extra', to='contacto.Contacto')),
            ],
            options={
                'ordering': ['contacto'],
            },
        ),
    ]
