# Generated by Django 3.0.6 on 2020-10-17 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo_contacto',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_extra', to='contacto.Contacto'),
        ),
    ]
