# Generated by Django 3.0.6 on 2020-10-29 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo',
            old_name='cmapos_extra',
            new_name='campos_extra',
        ),
    ]
