# Generated by Django 3.0.6 on 2020-10-29 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        ('contacto', '0002_auto_20201028_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo_contacto',
            name='valor',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='campos_extra',
            field=models.ManyToManyField(blank=True, related_name='grupos', to='contacto.CampoExtra'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='cuenta',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='marketing.Cuenta'),
        ),
    ]
