# Generated by Django 3.0.6 on 2020-10-31 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0003_auto_20201028_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={},
        ),
    ]
