# Generated by Django 3.0.6 on 2020-08-04 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing', '0002_auto_20200718_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=70)),
                ('sub_categoria', models.CharField(max_length=70)),
                ('tipo_ubicacion', models.CharField(max_length=15)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField()),
                ('imagen', models.FileField(upload_to=None)),
                ('resumen', models.CharField(max_length=1000)),
                ('id_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_cuenta', to='marketing.Cuenta')),
            ],
        ),
    ]
