# Generated by Django 3.0.6 on 2020-12-03 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=70)),
                ('sub_categoria', models.CharField(max_length=70)),
                ('ubicacion', models.TextField(blank=True)),
                ('fecha_hora_inicio', models.DateTimeField(null=True)),
                ('fecha_hora_fin', models.DateTimeField(null=True)),
                ('zona_horaria', models.CharField(blank=True, max_length=100)),
                ('resumen', models.CharField(blank=True, max_length=1000)),
                ('estatus', models.CharField(max_length=50)),
                ('imagen', models.CharField(blank=True, max_length=10)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('etiquetas', models.CharField(blank=True, max_length=1000)),
                ('componentes', models.TextField(blank=True)),
                ('boletos', models.TextField(blank=True)),
                ('id_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_cuenta', to='marketing.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenPrincipal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imegenes', to='eventos.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Asistente_Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('metodo_pago', models.CharField(blank=True, max_length=20)),
                ('monto_total', models.CharField(blank=True, max_length=10)),
                ('estatus_pago', models.CharField(blank=True, max_length=40)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizado', models.DateTimeField(auto_now=True)),
                ('boletos', models.CharField(blank=True, max_length=1000)),
                ('donacion', models.CharField(blank=True, max_length=1000)),
                ('detalles', models.CharField(blank=True, max_length=1000)),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistentes', to='eventos.Evento')),
            ],
        ),
    ]
