# Generated by Django 3.0.6 on 2020-08-04 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='zona_horaria',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Video_Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=260)),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_evento', to='eventos.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Tags_Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plabra', models.CharField(max_length=30)),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_evento', to='eventos.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Parrafo_Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parrafo', models.CharField(max_length=560)),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parrafo_evento', to='eventos.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Online_Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_evento', to='eventos.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Lugar_Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion1', models.CharField(max_length=200, null=True)),
                ('ciudad', models.CharField(max_length=60)),
                ('estado', models.CharField(max_length=60)),
                ('codigo_postal', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=100)),
                ('latitud', models.CharField(max_length=30, null=True)),
                ('longitud', models.CharField(max_length=30, null=True)),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugar_evento', to='eventos.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen_Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to=None)),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagen_evento', to='eventos.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Boleto_Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('cantida_total', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=250)),
                ('cantidad_minima', models.CharField(max_length=20)),
                ('cantidad_maxima', models.CharField(max_length=20)),
                ('canal_ventas', models.CharField(max_length=50)),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boleto_evento', to='eventos.Evento')),
            ],
        ),
    ]
