# Generated by Django 3.0.6 on 2020-10-31 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=4000)),
                ('posicion', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='parrafo_evento',
            name='id_evento',
        ),
        migrations.RemoveField(
            model_name='video_evento',
            name='id_evento',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='directorio_imagen',
        ),
        migrations.AddField(
            model_name='imagenprincipal',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imegen_principal', to='eventos.Evento'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Imagen_Evento',
        ),
        migrations.DeleteModel(
            name='Parrafo_Evento',
        ),
        migrations.DeleteModel(
            name='Video_Evento',
        ),
        migrations.AddField(
            model_name='componente',
            name='id_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parrafo_evento', to='eventos.Evento'),
        ),
    ]
