# Generated by Django 3.0.6 on 2020-10-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_auto_20201031_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_hora_fin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_hora_inicio',
            field=models.DateTimeField(null=True),
        ),
    ]
