# Generated by Django 3.0.6 on 2020-08-08 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_auto_20200808_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='diretorio_imagen',
            new_name='directorio_imagen',
        ),
    ]
