# Generated by Django 3.0.6 on 2020-08-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_auto_20200808_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar_evento',
            name='direccion2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lugar_evento',
            name='direccion1',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
