# Generated by Django 3.0.6 on 2020-11-01 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_auto_20201031_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenprincipal',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='imagenprincipal',
            name='cuenta',
        ),
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='imagenprincipal',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imegenes', to='eventos.Evento'),
        ),
    ]
