# Generated by Django 3.0.6 on 2020-11-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_auto_20201101_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='tipo',
            field=models.CharField(default='imagen', max_length=15),
            preserve_default=False,
        ),
    ]
