# Generated by Django 3.0.6 on 2020-08-08 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_auto_20200808_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags_evento',
            old_name='plabra',
            new_name='palabra',
        ),
    ]
