# Generated by Django 3.0.6 on 2020-11-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_componente_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
