# Generated by Django 3.0.6 on 2020-08-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_auto_20200808_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto_evento',
            name='precio',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
