# Generated by Django 3.0.6 on 2020-11-13 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_evento_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto_asistenteevento',
            name='id_asistencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='eventos.Asistente_Evento'),
        ),
        migrations.AlterField(
            model_name='boleto_asistenteevento',
            name='id_boleto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adquiridos', to='eventos.Boleto_Evento'),
        ),
    ]
