# Generated by Django 3.0.6 on 2020-08-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_boleto_evento_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen_evento',
            name='directorio_imagen',
            field=models.CharField(max_length=1000),
        ),
    ]
