# Generated by Django 3.0.6 on 2020-11-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_auto_20201112_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleto_evento',
            name='id_evento',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='id_evento',
        ),
        migrations.RemoveField(
            model_name='detalles_oxxopay_evento',
            name='id_asistencia',
        ),
        migrations.RemoveField(
            model_name='detalles_pagotarjeta_evento',
            name='id_asistencia',
        ),
        migrations.RemoveField(
            model_name='donacion_asistente_evento',
            name='id_asistencia',
        ),
        migrations.RemoveField(
            model_name='lugar_evento',
            name='id_evento',
        ),
        migrations.RemoveField(
            model_name='online_evento',
            name='id_evento',
        ),
        migrations.RemoveField(
            model_name='tags_evento',
            name='id_evento',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='tipo_ubicacion',
        ),
        migrations.AddField(
            model_name='asistente_evento',
            name='boletos',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='asistente_evento',
            name='detalles',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='asistente_evento',
            name='donacion',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='evento',
            name='boletos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='componentes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='etiquetas',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='evento',
            name='ubicacion',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Boleto_AsistenteEvento',
        ),
        migrations.DeleteModel(
            name='Boleto_Evento',
        ),
        migrations.DeleteModel(
            name='Componente',
        ),
        migrations.DeleteModel(
            name='Detalles_OxxoPay_Evento',
        ),
        migrations.DeleteModel(
            name='Detalles_PagoTarjeta_Evento',
        ),
        migrations.DeleteModel(
            name='Donacion_Asistente_Evento',
        ),
        migrations.DeleteModel(
            name='Lugar_Evento',
        ),
        migrations.DeleteModel(
            name='Online_Evento',
        ),
        migrations.DeleteModel(
            name='Tags_Evento',
        ),
    ]
