# Generated by Django 3.0.6 on 2020-08-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_auto_20200809_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen_evento',
            name='posicion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parrafo_evento',
            name='posicion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_evento',
            name='posicion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
