# Generated by Django 3.0.6 on 2020-08-21 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_auto_20200811_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistente_Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('metodo_pago', models.CharField(max_length=20)),
                ('monto_total', models.CharField(max_length=10)),
                ('estatus_pago', models.CharField(max_length=40)),
                ('fecha_agrgado', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizado', models.DateTimeField(auto_now=True)),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistente_evento', to='eventos.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Detalles_PagoTarjeta_Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pago', models.CharField(max_length=60)),
                ('id_orden', models.CharField(max_length=30)),
                ('id_asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardDetailspay_asistente', to='eventos.Asistente_Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Detalles_OxxoPay_Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_referencia', models.CharField(max_length=20)),
                ('id_asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oxxoDetails_asistente', to='eventos.Asistente_Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Boleto_AsistenteEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=10)),
                ('id_asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boleto_asistente', to='eventos.Asistente_Evento')),
                ('id_boleto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boleto_item', to='eventos.Boleto_Evento')),
            ],
        ),
    ]
