# Generated by Django 3.0.6 on 2020-11-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_auto_20201120_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistente_evento',
            name='estatus_pago',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='asistente_evento',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='asistente_evento',
            name='monto_total',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
