# Generated by Django 3.0.6 on 2020-11-25 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_auto_20201122_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistente_evento',
            old_name='fecha_agrgado',
            new_name='fecha_agregado',
        ),
    ]
