# Generated by Django 3.0.6 on 2020-09-12 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_auto_20200912_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online_evento',
            name='id_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_evento', to='eventos.Evento'),
        ),
    ]
