# Generated by Django 3.0.6 on 2020-10-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0018_auto_20201016_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='nombre_imagen',
        ),
        migrations.AddField(
            model_name='imagenprincipal',
            name='cliente',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagenprincipal',
            name='cuenta',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='directorio_imagen',
            field=models.CharField(max_length=10),
        ),
    ]
