# Generated by Django 3.0.6 on 2020-10-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0019_auto_20201016_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen_evento',
            name='directorio_imagen',
        ),
        migrations.AddField(
            model_name='imagen_evento',
            name='cliente',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagen_evento',
            name='cuenta',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
