# Generated by Django 3.0.6 on 2020-10-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0020_auto_20201017_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen_evento',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='imagen_evento',
            name='cuenta',
        ),
    ]
