# Generated by Django 3.0.6 on 2020-10-29 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacto', '0001_initial'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=500)),
                ('tipo_publicacion', models.CharField(max_length=20)),
                ('contenido', models.TextField()),
                ('estatus', models.CharField(max_length=30)),
                ('fecha_creado', models.DateField(auto_now=True)),
                ('id_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletin_cuenta', to='marketing.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenBoletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cuenta', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LinkBoletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000)),
                ('id_boletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='emailmarketing.Boletin')),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaBoletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SeenLinkBoletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visto', models.DateTimeField(auto_now_add=True)),
                ('id_contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactolink_seen', to='contacto.Contacto')),
                ('id_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistos', to='emailmarketing.LinkBoletin')),
            ],
        ),
        migrations.CreateModel(
            name='SeenContactoBoletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visto', models.DateTimeField(auto_now_add=True)),
                ('id_boletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistos_boletin', to='emailmarketing.Boletin')),
                ('id_contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacto_seen', to='contacto.Contacto')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoEnvioBoletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_boletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletin_grupo', to='emailmarketing.Boletin')),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_boletin', to='contacto.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='FechaHoraPublicacionBoletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=20)),
                ('hora', models.CharField(max_length=10)),
                ('ids_grupos', models.TextField()),
                ('id_boletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fecha_programado', to='emailmarketing.Boletin')),
            ],
        ),
        migrations.CreateModel(
            name='EnvioBoletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids_contactos', models.TextField()),
                ('ids_grupos', models.TextField()),
                ('id_boletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='emailmarketing.Boletin')),
            ],
        ),
    ]
