# Generated by Django 3.0.6 on 2020-09-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailmarketing', '0002_auto_20200926_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletin',
            name='categoria',
            field=models.CharField(default='Turismo', max_length=100),
            preserve_default=False,
        ),
    ]
