# Generated by Django 3.0.6 on 2020-11-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailmarketing', '0002_auto_20201122_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletin',
            name='contenido',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='boletin',
            name='estatus',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
