# Generated by Django 3.0.6 on 2020-11-25 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailmarketing', '0003_auto_20201122_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seencontactoboletin',
            name='id_boletin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_vistos', to='emailmarketing.Boletin'),
        ),
        migrations.AlterField(
            model_name='seenlinkboletin',
            name='boletin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_vistos', to='emailmarketing.Boletin'),
        ),
    ]
