# Generated by Django 3.0.6 on 2020-09-28 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
        ('emailmarketing', '0004_auto_20200926_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeenContactoBoletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SeenContactoBoletinPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SeenLinkBoletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactolink_seen', to='contacto.Contacto')),
                ('id_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_seen', to='emailmarketing.LinkBoletin')),
            ],
        ),
        migrations.CreateModel(
            name='SeenLinkBoletinPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactolink_seen_post', to='contacto.Contacto')),
                ('id_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_seen_post', to='emailmarketing.LinkBoletin')),
            ],
        ),
        migrations.AddField(
            model_name='boletin',
            name='estatus',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ContactoLinkBoletin',
        ),
        migrations.AddField(
            model_name='seencontactoboletinpost',
            name='id_boletin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletin_seen_post', to='emailmarketing.Boletin'),
        ),
        migrations.AddField(
            model_name='seencontactoboletinpost',
            name='id_contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacto_seen_post', to='contacto.Contacto'),
        ),
        migrations.AddField(
            model_name='seencontactoboletin',
            name='id_boletin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletin_seen', to='emailmarketing.Boletin'),
        ),
        migrations.AddField(
            model_name='seencontactoboletin',
            name='id_contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacto_seen', to='contacto.Contacto'),
        ),
    ]
