# Generated by Django 3.0.6 on 2020-09-29 01:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emailmarketing', '0005_auto_20200928_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seenlinkboletinpost',
            name='id_contacto',
        ),
        migrations.RemoveField(
            model_name='seenlinkboletinpost',
            name='id_link',
        ),
        migrations.AddField(
            model_name='seencontactoboletin',
            name='fecha_visto',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seenlinkboletin',
            name='fecha_visto',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SeenContactoBoletinPost',
        ),
        migrations.DeleteModel(
            name='SeenLinkBoletinPost',
        ),
    ]
