# Generated by Django 3.0.6 on 2020-09-29 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailmarketing', '0006_auto_20200928_2052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FechaHoraPublicacionBoletin',
        ),
    ]
