# Generated by Django 3.0.6 on 2020-09-29 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailmarketing', '0007_delete_fechahorapublicacionboletin'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaHoraPublicacionBoletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=20)),
                ('hora', models.CharField(max_length=10)),
                ('id_boletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fecha_boletin', to='emailmarketing.Boletin')),
            ],
        ),
    ]
