# Generated by Django 3.0.6 on 2020-09-29 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailmarketing', '0008_fechahorapublicacionboletin'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkboletin',
            name='id_boletin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='link_boletin', to='emailmarketing.Boletin'),
            preserve_default=False,
        ),
    ]
