# Generated by Django 3.0.6 on 2020-09-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailmarketing', '0009_linkboletin_id_boletin'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechahorapublicacionboletin',
            name='ids_grupos',
            field=models.CharField(default='1', max_length=250),
            preserve_default=False,
        ),
    ]
