# Generated by Django 3.0.6 on 2020-09-29 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20200718_1650'),
        ('emailmarketing', '0010_fechahorapublicacionboletin_ids_grupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletin',
            name='id_cuenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='boletin_cuenta', to='marketing.Cuenta'),
            preserve_default=False,
        ),
    ]
