# Generated by Django 3.0.6 on 2020-10-01 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emailmarketing', '0012_auto_20200930_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletin',
            name='fecha_creado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
