# Generated by Django 3.0.6 on 2020-10-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailmarketing', '0013_boletin_fecha_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='envioboletin',
            name='ids_grupos',
            field=models.TextField(default='1,2,3,4,'),
            preserve_default=False,
        ),
    ]
