# Generated by Django 3.0.6 on 2020-07-24 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampoExtra',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('razon_social', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=30)),
                ('dominio', models.CharField(max_length=100)),
                ('giro', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('estatus', models.CharField(max_length=30)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_de_cliente', to='marketing_digital.Cliente')),
            ],
            options={
                'ordering': ['id_cliente'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cuenta', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cuenta_del_grupo', to='marketing_digital.Cuenta')),
            ],
            options={
                'ordering': ['cuenta'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('correo', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=30)),
                ('estatus', models.CharField(max_length=30)),
                ('imagen', models.CharField(max_length=100)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_usuario', to='marketing_digital.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('id_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_cuenta', to='marketing_digital.Cuenta')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario', to='marketing_digital.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='contacto_grupo', to='marketing_digital.Contacto')),
                ('grupo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='grupo_contacto', to='marketing_digital.Grupo')),
            ],
            options={
                'ordering': ['grupo'],
            },
        ),
        migrations.CreateModel(
            name='CampoExtra_Grupo',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('campo_extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campo_grupo', to='marketing_digital.CampoExtra')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gupo_campo', to='marketing_digital.Grupo')),
            ],
            options={
                'ordering': ['grupo'],
            },
        ),
        migrations.CreateModel(
            name='Campo_Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=70)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_digital.CampoExtra')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_digital.Contacto')),
            ],
            options={
                'ordering': ['contacto'],
            },
        ),
    ]
