# Generated by Django 3.0.6 on 2020-11-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encuenta', models.CharField(max_length=10)),
                ('imagen', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
    ]
