# Generated by Django 3.0.6 on 2020-11-13 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='imagen',
        ),
    ]
