# Generated by Django 3.0.6 on 2020-11-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_remove_imagen_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagen',
            old_name='encuenta',
            new_name='encuesta',
        ),
    ]
