# Generated by Django 3.0.6 on 2020-11-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0003_auto_20201113_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('presentacion', models.CharField(max_length=1000)),
                ('instrucciones', models.CharField(max_length=1000)),
                ('imagen', models.CharField(max_length=10)),
                ('anonima', models.BooleanField()),
                ('poderacion', models.BooleanField()),
                ('paginacion', models.CharField(max_length=10)),
                ('preguntas_json', models.TextField()),
                ('despedida', models.CharField(max_length=1000)),
            ],
        ),
    ]
