# Generated by Django 3.0.6 on 2020-11-14 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0005_auto_20201114_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encuesta',
            old_name='poderacion',
            new_name='ponderacion',
        ),
    ]
