# Generated by Django 3.0.6 on 2020-11-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0006_auto_20201114_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='estatus',
            field=models.CharField(default='borrador', max_length=20),
            preserve_default=False,
        ),
    ]
