# Generated by Django 3.0.6 on 2020-11-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0007_encuesta_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='nombre',
            field=models.CharField(max_length=35),
        ),
    ]
