# Generated by Django 3.0.6 on 2020-11-16 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0010_encuestado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encuestado',
            old_name='respouesta_json',
            new_name='respuestas_json',
        ),
    ]
