# Generated by Django 3.0.6 on 2020-11-17 03:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0011_auto_20201116_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestado',
            name='creado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
