# Generated by Django 3.0.6 on 2020-11-17 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0012_encuestado_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestado',
            name='encuesta',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, related_name='encuestados', to='encuestas.Encuesta'),
            preserve_default=False,
        ),
    ]
